//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Funcionario
    {
        [Display(Name = "Código")]
        public int id { get; set; }

        [Display(Name = "Foto")]
        public string foto { get; set; }

        [Required]
        [Display(Name = "Nome")]
        [StringLength(60, ErrorMessage = "O {0} deve ser de pelo menos {0} caracteres.", MinimumLength = 2)]
        public string nome_completo { get; set; }

        [Display(Name = "Endereço")]
        public string endereco { get; set; }

        [Display(Name = "Cidade")]
        public string cidade { get; set; }

        [Display(Name = "Descrição do Cargo")]
        public string descricao_cargo { get; set; }

        [Display(Name = "Salário")]
        public Nullable<decimal> salario { get; set; }

        [Display(Name = "CEP")]
        public string cep { get; set; }

        [Display(Name = "Telefone")]
        public string telefone { get; set; }

        [Display(Name = "Selecione para Remover a Foto")]
        public Boolean deleteFoto { get; set; }
    }
}
